---
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # TODO: "workspaces/"の後のディレクトリ名を、テンプレ使用先のディレクトリ名に変更
      - ../:/workspaces/go-repository-template:cached
    command: sleep infinity
    environment:
      - TZ=Asia/Tokyo
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

# TODO: volume, network名は適宜調整
volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
