---
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces/test-mcp:cached
    command: sleep infinity
    environment:
      - TZ=Asia/Tokyo
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    volumes:
      - test-mcp-postgres-data:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test-mcp-postgres-data:

networks:
  backend:
    driver: bridge
