root = "."
tmp_dir = "/tmp/services_batch"

[build]
bin = "/tmp/services_batch/main"
cmd = "go build -o /tmp/services_batch/main ./cmd/batch/" # TODO: build対象の.goのディレクトリを設定
full_bin = "ENV=local /tmp/services_batch/main"
delay = 1000
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_test.go"]
include_ext = ["go"]
