root = "."
tmp_dir = "/tmp/services_api"

[build]
bin = "/tmp/services_api/main"
cmd = "go build -o /tmp/services_api/main ./cmd/api/" # TODO: build対象の.goのディレクトリを設定
full_bin = "ENV=local /tmp/services_api/main"
delay = 1000
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_test.go"]
include_ext = ["go"]
